-- ============================================================
-- TEMPLATE COMERCIAL V5.1 - INSTALAÇÃO BASE NO SUPABASE
-- ============================================================
-- Execute em um projeto NOVO do Supabase, no SQL Editor.
-- Depois crie o usuário administrador em Authentication > Users
-- e execute o bloco FINAL deste arquivo com o UID correto.

-- 1) TABELA DE PRODUTOS
create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  "preço" numeric(12,2) not null default 0,
  categoria_principal text not null,
  subcategoria text not null,
  descricao text,
  image_url text,
  disponivel boolean not null default true,
  destaque boolean not null default false,
  constraint produtos_nome_nao_vazio check (length(trim(nome)) > 0),
  constraint produtos_preco_nao_negativo check ("preço" >= 0),
  constraint produtos_categoria_nao_vazia check (length(trim(categoria_principal)) > 0),
  constraint produtos_subcategoria_nao_vazia check (length(trim(subcategoria)) > 0)
);

-- 2) CONFIGURAÇÕES DA LOJA
create table if not exists public.configuracoes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome_loja text not null default 'Minha Loja',
  whatsapp text,
  instagram text,
  endereco text,
  horario text,
  texto_hero text,
  texto_sobre text,
  logo_url text,
  hero_titulo text,
  hero_slogan text,
  hero_botao_texto text,
  sobre_titulo text,
  footer_titulo text,
  footer_subtitulo text,
  tema text not null default 'noir_gold'
);

insert into public.configuracoes (id, nome_loja, tema)
values (1, 'Minha Loja', 'noir_gold')
on conflict (id) do nothing;

-- 3) ADMINISTRADORES
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.produtos enable row level security;
alter table public.configuracoes enable row level security;
alter table public.admins enable row level security;

revoke all on table public.admins from anon, authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admins where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- 4) POLICIES DAS TABELAS
drop policy if exists "public read available products" on public.produtos;
drop policy if exists "admin read all products" on public.produtos;
drop policy if exists "admin insert products" on public.produtos;
drop policy if exists "admin update products" on public.produtos;
drop policy if exists "admin delete products" on public.produtos;

create policy "public read available products" on public.produtos
for select to anon using (disponivel = true);
create policy "admin read all products" on public.produtos
for select to authenticated using (public.is_admin());
create policy "admin insert products" on public.produtos
for insert to authenticated with check (public.is_admin());
create policy "admin update products" on public.produtos
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin delete products" on public.produtos
for delete to authenticated using (public.is_admin());

drop policy if exists "public read settings" on public.configuracoes;
drop policy if exists "admin read settings" on public.configuracoes;
drop policy if exists "admin update settings" on public.configuracoes;

create policy "public read settings" on public.configuracoes
for select to anon using (true);
create policy "admin read settings" on public.configuracoes
for select to authenticated using (public.is_admin());
create policy "admin update settings" on public.configuracoes
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- 5) STORAGE / BUCKETS
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('produtos', 'produtos', true, 8388608, array['image/jpeg','image/png','image/webp']),
  ('site-assets', 'site-assets', true, 8388608, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "admin upload product images" on storage.objects;
drop policy if exists "admin update product images" on storage.objects;
drop policy if exists "admin delete product images" on storage.objects;
drop policy if exists "admin upload site assets" on storage.objects;
drop policy if exists "admin update site assets" on storage.objects;
drop policy if exists "admin delete site assets" on storage.objects;

create policy "admin upload product images" on storage.objects
for insert to authenticated with check (bucket_id = 'produtos' and public.is_admin());
create policy "admin update product images" on storage.objects
for update to authenticated using (bucket_id = 'produtos' and public.is_admin())
with check (bucket_id = 'produtos' and public.is_admin());
create policy "admin delete product images" on storage.objects
for delete to authenticated using (bucket_id = 'produtos' and public.is_admin());

create policy "admin upload site assets" on storage.objects
for insert to authenticated with check (bucket_id = 'site-assets' and public.is_admin());
create policy "admin update site assets" on storage.objects
for update to authenticated using (bucket_id = 'site-assets' and public.is_admin())
with check (bucket_id = 'site-assets' and public.is_admin());
create policy "admin delete site assets" on storage.objects
for delete to authenticated using (bucket_id = 'site-assets' and public.is_admin());

-- ============================================================
-- ETAPA FINAL - EXECUTE SOMENTE DEPOIS DE CRIAR O USUÁRIO
-- Authentication > Users > Add user
-- Copie o UID e substitua COLE_AQUI_O_UID_DO_ADMIN abaixo.
-- Remova os dois traços (--) das duas linhas para executar.
-- ============================================================
-- insert into public.admins (user_id)
-- values ('COLE_AQUI_O_UID_DO_ADMIN'::uuid)
-- on conflict (user_id) do nothing;
